import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"

import One from "../public/examples/one.png"
import Two from "../public/examples/two.png"
import Three from "../public/examples/three.png"
import Code from "../public/code.png"

const Home: NextPage = () => {
  return (
  <div>
    <div className="place-items-center justify-center flex flex-col mx-auto mt-32 px-8">
      <Head>
        <title>Tilde</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="lg:flex justify-center">
        <div className="self-center">
          <h1 className="text-6xl font-bold w-3/4">An easier way to take notes</h1>
          <p className="text-gray-600 w-2/3 text-xl pt-4">Tilde is a simple, open source way to take your notes.</p>
          <button
              className="bg-gray-100 py-4 px-6 rounded-xl mt-8 text-medium flex border-2 border-transparent hover:border-gray-200 cursor-not-allowed"
          >
            Download
          </button>
        </div>
        <Image
            src={One}
            alt="A screenshot of Tilde in action"
            className="w-1/2 rounded-lg"
        />
      </div>
      <div className="mt-64 md:flex space-x-64 justify-center">
        <Image
            src={Two}
            alt="A screenshot of Tilde in action"
            className="w-1/2 rounded-lg"
        />
        <div className="self-center">
          <h1 className="font-semibold text-4xl">
            Simple
          </h1>
          <p className="mt-4 text-xl w-3/4">
            Tilde helps remove all distractions. It’s just you, and your writing.
          </p>
          <button
              className="bg-gray-100 py-4 px-6 rounded-xl mt-8 text-medium flex border-2 border-transparent hover:border-gray-200 cursor-not-allowed"
          >
            Check out some examples
          </button>
        </div>
      </div>
      <div className="mt-64 flex space-x-64 justify-center">
        <div className="self-center">
          <h1 className="font-semibold text-4xl">
            Effortless
          </h1>
          <p className="mt-4 text-xl w-3/4">
            Right from installation, Tilde is ready to use. No configuration required.
          </p>
          <button
              className="bg-gray-100 py-4 px-6 rounded-xl mt-8 text-medium flex border-2 border-transparent hover:border-gray-200 cursor-not-allowed"
          >
            Get started
          </button>
        </div>
        <Image
            src={Three}
            alt="A screenshot of Tilde in action"
            className="w-1/2 rounded-lg"
        />
      </div>
      <div className="mt-32 border-t">
        <div className="mt-32 flex space-x-64 justify-center mb-64">
        <div>
          <h1 className="font-semibold text-4xl w-2/3">
            Oh, and it’s all open source
          </h1>
          <p className="mt-4 text-xl w-2/3">
            That’s right, all of it is open source. That means anyone who wants to can view the code.
          </p>
          <Link
              href="https://github.com/developedbytoby/tilde"
              target="_blank"
              rel="noopener norefferer"
          >
            <button
                className="bg-gray-100 py-4 px-6 rounded-xl mt-8 text-medium flex border-2 border-transparent hover:border-gray-200"
            >
              See the code
            </button>
          </Link>
        </div>
        <Image
            src={Code}
            alt="A screenshot of Tilde in action"
            className="w-1/2 rounded-lg border"
        />
        </div>
      </div>
      <div className="mb-64 justify-center text-center">
        <Image
            src="https://github.com/developedbytoby/tilde/raw/master/resources/icon.png"
            alt="Tilde app icon"
            height="128"
            width="128"
            className="mx-auto mb-16"
        />
        <h1 className="text-6xl font-bold w-3/4 mx-auto">So, what are you waiting for?</h1>
        <p className="text-gray-600 text-xl mt-8">
          Get started right now for totally free.
        </p>
        <button
            className="bg-gray-100 py-4 px-6 rounded-xl mt-8 text-medium flex border-2 border-transparent hover:border-gray-200 mx-auto cursor-not-allowed"
        >
          Download
        </button>
      </div>
      <h1 className="mb-8 text-xl">Built by <Link
            href="https://tobyb.dev"
            target="_blank"
            rel="noopener norefferer"
            className="underline"
      >
        Toby
      </Link>.</h1>
    </div>
  </div>
  )
}

export default Home
