import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import DownloadIcon from "../components/download"

const Home: NextPage = () => {
  return (
  <div>
    <div className="grid mt-32 place-items-center space-y-4">
      <Head>
        <title>Tilde</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-2/6 mb-8">
        <h1 className="text-7xl font-bold">An easy way to take notes.</h1>
        <div className="space-x-4 flex">
        <button
          className="bg-gray-100 py-4 px-6 rounded-xl mt-8 text-medium flex border-2 border-transparent hover:border-gray-200"
        >
          Download &nbsp; <DownloadIcon/>
        </button>
        <button
          className="bg-black py-4 px-6 rounded-xl mt-8 text-medium flex border-2 border-black text-white hover:bg-transparent hover:text-black"
        >
          GitHub
        </button>
        </div>
      </div>
    </div>
    <img
      className="fixed"
      src="/example.png"
    />
  </div>
  )
}

export default Home
